# Generated by Django 2.2.4 on 2019-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='overview_images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_detail',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
