# Generated by Django 2.2.4 on 2019-08-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190822_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_detail',
            field=models.CharField(max_length=30),
        ),
    ]
